//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHTHUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HINHTHUC()
        {
            this.THUONGKILUATs = new HashSet<THUONGKILUAT>();
        }
    
        public int MAHT { get; set; }
        public string HINHTHUC1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUONGKILUAT> THUONGKILUATs { get; set; }
    }
}
