//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public int MALUONG { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> MATKL { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string LUONG1 { get; set; }
        public string BHXH { get; set; }
        public string BHYT { get; set; }
    
        public virtual THUONGKILUAT THUONGKILUAT { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
