//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BANGCAPs = new HashSet<BANGCAP>();
            this.BANGCHAMCONGs = new HashSet<BANGCHAMCONG>();
            this.HOPDONGs = new HashSet<HOPDONG>();
            this.LUONGs = new HashSet<LUONG>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
            this.QTCTs = new HashSet<QTCT>();
        }
    
        public int MANV { get; set; }
        public Nullable<int> MAPB { get; set; }
        public Nullable<int> MACV { get; set; }
        public string HOTENNV { get; set; }
        public string DIACHI { get; set; }
        public string GIOITINH { get; set; }
        public string NGAYSINH { get; set; }
        public string CMND { get; set; }
        public string QUEQUAN { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DANTOC { get; set; }
        public string SOBH { get; set; }
        public string IMG_PATH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGCAP> BANGCAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGCHAMCONG> BANGCHAMCONGs { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUONG> LUONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QTCT> QTCTs { get; set; }
    }
}
